/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloTest {
    @Test void appHasAGreeting() {
        Hello classUnderTest = new Hello();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testFoo() {
        Hello classUnderTest = new Hello();
        assertEquals(6, classUnderTest.foo(2, 3));
    }
}
