/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.project;

public class Hello {
    public String getGreeting() {
        return "Hello World!";
    }

    public int foo(int x, int y) { return x * y; }

    public static void main(String[] args) {
        System.out.println(new Hello().getGreeting());
    }
}
