name: Java CI with Gradle

on:
  push:

jobs:
  gradle-test-with-different-JDK:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: ['11', '17']

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk_version }}
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
